enableScripts: false

nodeLinker: pnp

pnpFallbackMode: all

pnpMode: loose

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - win32
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-4.6.0.cjs
